/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as AdmissionIndexRouteImport } from './routes/admission.index'
import { Route as StaffForgotPasswordRouteImport } from './routes/staff.forgot-password'
import { Route as StaffDashboardRouteImport } from './routes/staff.dashboard'
import { Route as DebugFaviconsRouteImport } from './routes/debug.favicons'
import { Route as AdmissionRegisterRouteImport } from './routes/admission.register'
import { Route as AdmissionDashboardRouteImport } from './routes/admission.dashboard'
import { Route as AdmissionApplyRouteImport } from './routes/admission.apply'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const AdmissionIndexRoute = AdmissionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdmissionRoute,
} as any)
const StaffForgotPasswordRoute = StaffForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StaffRoute,
} as any)
const DebugFaviconsRoute = DebugFaviconsRouteImport.update({
  id: '/debug/favicons',
  path: '/debug/favicons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRegisterRoute = AdmissionRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AdmissionRoute,
} as any)
const AdmissionDashboardRoute = AdmissionDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdmissionRoute,
} as any)
const AdmissionApplyRoute = AdmissionApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AdmissionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admission': typeof AdmissionRouteWithChildren
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/staff': typeof StaffRouteWithChildren
  '/admission/apply': typeof AdmissionApplyRoute
  '/admission/dashboard': typeof AdmissionDashboardRoute
  '/admission/register': typeof AdmissionRegisterRoute
  '/debug/favicons': typeof DebugFaviconsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/forgot-password': typeof StaffForgotPasswordRoute
  '/admission/': typeof AdmissionIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/admission/apply': typeof AdmissionApplyRoute
  '/admission/dashboard': typeof AdmissionDashboardRoute
  '/admission/register': typeof AdmissionRegisterRoute
  '/debug/favicons': typeof DebugFaviconsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/forgot-password': typeof StaffForgotPasswordRoute
  '/admission': typeof AdmissionIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admission': typeof AdmissionRouteWithChildren
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/staff': typeof StaffRouteWithChildren
  '/admission/apply': typeof AdmissionApplyRoute
  '/admission/dashboard': typeof AdmissionDashboardRoute
  '/admission/register': typeof AdmissionRegisterRoute
  '/debug/favicons': typeof DebugFaviconsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/forgot-password': typeof StaffForgotPasswordRoute
  '/admission/': typeof AdmissionIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admission'
    | '/contact'
    | '/news'
    | '/staff'
    | '/admission/apply'
    | '/admission/dashboard'
    | '/admission/register'
    | '/debug/favicons'
    | '/staff/dashboard'
    | '/staff/forgot-password'
    | '/admission/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/news'
    | '/admission/apply'
    | '/admission/dashboard'
    | '/admission/register'
    | '/debug/favicons'
    | '/staff/dashboard'
    | '/staff/forgot-password'
    | '/admission'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/admission'
    | '/contact'
    | '/news'
    | '/staff'
    | '/admission/apply'
    | '/admission/dashboard'
    | '/admission/register'
    | '/debug/favicons'
    | '/staff/dashboard'
    | '/staff/forgot-password'
    | '/admission/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissionRoute: typeof AdmissionRouteWithChildren
  ContactRoute: typeof ContactRoute
  NewsRoute: typeof NewsRoute
  StaffRoute: typeof StaffRouteWithChildren
  DebugFaviconsRoute: typeof DebugFaviconsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/admission/': {
      id: '/admission/'
      path: '/'
      fullPath: '/admission/'
      preLoaderRoute: typeof AdmissionIndexRouteImport
      parentRoute: typeof AdmissionRoute
    }
    '/staff/forgot-password': {
      id: '/staff/forgot-password'
      path: '/forgot-password'
      fullPath: '/staff/forgot-password'
      preLoaderRoute: typeof StaffForgotPasswordRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof StaffRoute
    }
    '/debug/favicons': {
      id: '/debug/favicons'
      path: '/debug/favicons'
      fullPath: '/debug/favicons'
      preLoaderRoute: typeof DebugFaviconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission/register': {
      id: '/admission/register'
      path: '/register'
      fullPath: '/admission/register'
      preLoaderRoute: typeof AdmissionRegisterRouteImport
      parentRoute: typeof AdmissionRoute
    }
    '/admission/dashboard': {
      id: '/admission/dashboard'
      path: '/dashboard'
      fullPath: '/admission/dashboard'
      preLoaderRoute: typeof AdmissionDashboardRouteImport
      parentRoute: typeof AdmissionRoute
    }
    '/admission/apply': {
      id: '/admission/apply'
      path: '/apply'
      fullPath: '/admission/apply'
      preLoaderRoute: typeof AdmissionApplyRouteImport
      parentRoute: typeof AdmissionRoute
    }
  }
}

interface AdmissionRouteChildren {
  AdmissionApplyRoute: typeof AdmissionApplyRoute
  AdmissionDashboardRoute: typeof AdmissionDashboardRoute
  AdmissionRegisterRoute: typeof AdmissionRegisterRoute
  AdmissionIndexRoute: typeof AdmissionIndexRoute
}

const AdmissionRouteChildren: AdmissionRouteChildren = {
  AdmissionApplyRoute: AdmissionApplyRoute,
  AdmissionDashboardRoute: AdmissionDashboardRoute,
  AdmissionRegisterRoute: AdmissionRegisterRoute,
  AdmissionIndexRoute: AdmissionIndexRoute,
}

const AdmissionRouteWithChildren = AdmissionRoute._addFileChildren(
  AdmissionRouteChildren,
)

interface StaffRouteChildren {
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffForgotPasswordRoute: typeof StaffForgotPasswordRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffDashboardRoute: StaffDashboardRoute,
  StaffForgotPasswordRoute: StaffForgotPasswordRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissionRoute: AdmissionRouteWithChildren,
  ContactRoute: ContactRoute,
  NewsRoute: NewsRoute,
  StaffRoute: StaffRouteWithChildren,
  DebugFaviconsRoute: DebugFaviconsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
